# Email config
subject: "Alert - Oxygen level"
email: "sender@gmail.com"
password: "XXXXXXXX"
recipients:
  - "email@hotmail.com"
  - "email@gmail.com"


# Serial config
port: 9600
com_port: "/dev/cu.usbmodem14101"
o2_th: 200
sleep_time: 900
